import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,readFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import ffmpeg from 'ffmpeg-static';
const jobs=new Map();
const outputDir=path.join(tmpdir(),'ai-video-commercials');
const TOKEN=process.env.REPLICATE_API_TOKEN;
const MODEL=process.env.REPLICATE_MODEL||'minimax/video-01';
const PASSWORD=process.env.STUDIO_ACCESS_PASSWORD;
const MAX=3;
let active=0;
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Commercial Studio</title><style>body{background:#08100e;color:#f5fff9;font:16px system-ui;margin:0}main{max-width:740px;margin:35px auto;padding:20px}a{color:#51ee98}h1{font-size:clamp(28px,5vw,45px)}.panel{background:#12201b;border:1px solid #345342;border-radius:20px;padding:25px}label{display:block;margin-top:17px;margin-bottom:6px}input,textarea,select{width:100%;box-sizing:border-box;background:#07120c;border:1px solid #476653;color:white;padding:13px;border-radius:9px;font:inherit}textarea{height:100px}button{width:100%;margin-top:22px;padding:15px;background:#45e58b;border:0;border-radius:9px;font-weight:bold;font-size:16px}button:disabled{opacity:.5}video{width:100%;margin-top:18px}#status{white-space:pre-wrap;line-height:1.5;margin-top:20px}small{color:#adc4b7}</style></head><body><main><a href="/">← Single video generator</a><h1>30-Second Commercial Studio</h1><p>Build a six-scene video ad with a clear message and call to action.</p><div class="panel"><label>Studio password</label><input type="password" id="password" autocomplete="off" placeholder="Configured in Render"><label>Business name</label><input id="business" maxlength="100" placeholder="AutoMake AI"><label>What does the business do?</label><textarea id="description" maxlength="700" placeholder="Automates customer follow-ups and appointment booking"></textarea><label>Call to action</label><input id="cta" maxlength="150" placeholder="Book a free demo today"><label>Format</label><select id="ratio"><option value="9:16">Vertical 9:16</option><option value="16:9">Landscape 16:9</option><option value="1:1">Square 1:1</option></select><button id="go">Generate 30-second commercial</button><small>Generates six provider clips and combines them into an MP4. Costs may be significant. Text is used in prompts, not guaranteed as readable on-screen captions. Voiceover/music are not yet included.</small><div id="status" role="status"></div><video id="video" controls playsinline hidden></video><a id="download" hidden download="commercial.mp4">Download commercial</a></div></main><script>
const $=id=>document.getElementById(id),b=$('go'),status=$('status'),video=$('video'),link=$('download');
b.onclick=async()=>{b.disabled=true;video.hidden=true;link.hidden=true;status.textContent='Submitting commercial…';try{let r=await fetch('/api/commercial',{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Password':$('password').value},body:JSON.stringify({business:$('business').value,description:$('description').value,cta:$('cta').value,ratio:$('ratio').value})});let d=await r.json();if(!r.ok)throw Error(d.error);const id=d.id;for(let i=0;i<360;i++){await new Promise(ok=>setTimeout(ok,5000));r=await fetch('/api/commercial/'+id,{headers:{'X-Studio-Password':$('password').value}});d=await r.json();if(!r.ok)throw Error(d.error);status.textContent=d.message||d.status;if(d.status==='failed')throw Error(d.error||'Generation failed');if(d.status==='complete'){const u='/api/commercial/'+id+'/video?password='+encodeURIComponent($('password').value);video.src=u;video.hidden=false;link.href=u;link.hidden=false;return}}throw Error('Still running. Please contact support with your job ID: '+id)}catch(e){status.textContent='Error: '+e.message}finally{b.disabled=false}};
</script></body></html>`;
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
async function provider(url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:'Bearer '+TOKEN,'Content-Type':'application/json',...opts.headers}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(JSON.stringify(d).slice(0,400));return d}
function run(args){return new Promise((resolve,reject)=>{const p=spawn(ffmpeg,args,{stdio:['ignore','ignore','pipe']});let err='';p.stderr.on('data',x=>err=(err+x).slice(-2500));p.on('error',reject);p.on('close',c=>c===0?resolve():reject(Error('FFmpeg failed: '+err.slice(-350))))})}
async function makeClip(prompt){const parts=MODEL.split('/');if(parts.length!==2)throw Error('REPLICATE_MODEL must be owner/model');let d=await provider('https://api.replicate.com/v1/models/'+parts.map(encodeURIComponent).join('/')+'/predictions',{method:'POST',body:JSON.stringify({input:{prompt}})});for(let i=0;i<180;i++){if(d.status==='succeeded'){const u=Array.isArray(d.output)?d.output.find(x=>typeof x==='string'):d.output;if(typeof u!=='string'||!u.startsWith('https://'))throw Error('Provider did not return video URL');return u}if(['failed','canceled'].includes(d.status))throw Error('Video provider: '+(d.error||d.status));await new Promise(ok=>setTimeout(ok,5000));d=await provider('https://api.replicate.com/v1/predictions/'+encodeURIComponent(d.id))}throw Error('Provider timed out')}
async function build(job,data){active++;const folder=await mkdtemp(path.join(tmpdir(),'commercial-'));try{job.status='running';const scenes=[`Problem: a customer needs help from ${data.business}, dramatic opening`,`Introduce ${data.business} as the solution, confident brand commercial`,`Show the service in action: ${data.description}`,`Happy customers benefit from ${data.description}`,`Success and momentum, professional business commercial for ${data.business}`,`Final inspiring call to action: ${data.cta} for ${data.business}`];const size=data.ratio==='9:16'?'720:1280':data.ratio==='1:1'?'720:720':'1280:720';const clips=[];for(let i=0;i<scenes.length;i++){job.message='Generating scene '+(i+1)+' of 6 (provider may take several minutes per scene)';const prompt=`Create a 5-second visually coherent advertising video shot. ${scenes[i]}. Business: ${data.business}. ${data.description}. ${data.ratio} composition. Cinematic, polished, professional. No illegible text.`;const url=await makeClip(prompt);const r=await fetch(url);if(!r.ok)throw Error('Unable to download scene '+(i+1));const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length>80*1024*1024)throw Error('Clip too large');const raw=path.join(folder,'raw'+i+'.mp4');const clip=path.join(folder,'clip'+i+'.mp4');await writeFile(raw,bytes);await run(['-y','-i',raw,'-t','5','-vf',`scale=${size}:force_original_aspect_ratio=decrease,pad=${size}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=24`,'-an','-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p',clip]);clips.push(clip)}
job.message='Stitching six scenes into a 30-second MP4';await mkdir(outputDir,{recursive:true});const list=path.join(folder,'list.txt');await writeFile(list,clips.map(p=>"file '"+p.replace(/'/g,"'\\''")+"'").join('\n'));const target=path.join(outputDir,job.id+'.mp4');await run(['-y','-f','concat','-safe','0','-i',list,'-c','copy',target]);job.status='complete';job.message='Commercial ready to download';job.file=target}catch(e){job.status='failed';job.error=e.message;job.message='Generation failed'}finally{active--;await rm(folder,{recursive:true,force:true})}}
export async function commercialHandler(req,res,url){if(url.pathname==='/commercial'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(html);return true}if(!url.pathname.startsWith('/api/commercial'))return false;if(!PASSWORD){json(res,503,{error:'Set STUDIO_ACCESS_PASSWORD in Render before using paid video generation.'});return true}const given=req.headers['x-studio-password']||(url.pathname.endsWith('/video')?url.searchParams.get('password'):'');const a=Buffer.from(String(given||'')),b=Buffer.from(PASSWORD);if(a.length!==b.length||!crypto.timingSafeEqual(a,b)){json(res,401,{error:'Incorrect studio password'});return true}
if(url.pathname==='/api/commercial'&&req.method==='POST'){if(!TOKEN){json(res,503,{error:'Set REPLICATE_API_TOKEN in Render'});return true}if(active>=MAX){json(res,429,{error:'Studio is busy. Try again later.'});return true}try{let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>6000)throw Error('Request too large')}const d=JSON.parse(raw);for(const k of ['business','description','cta'])if(typeof d[k]!=='string'||!d[k].trim()||d[k].length>800)throw Error('Missing or invalid '+k);if(!['9:16','16:9','1:1'].includes(d.ratio))throw Error('Invalid aspect ratio');const id=crypto.randomUUID(),job={id,status:'queued',message:'Queued'};jobs.set(id,job);void build(job,d);json(res,202,{id,status:job.status});return true}catch(e){json(res,400,{error:e.message});return true}}
const match=url.pathname.match(/^\/api\/commercial\/([a-f0-9-]+)(\/video)?$/);if(match&&req.method==='GET'){const job=jobs.get(match[1]);if(!job){json(res,404,{error:'Unknown or expired job'});return true}if(match[2]){if(job.status!=='complete'){json(res,409,{error:'Video not ready'});return true}const data=await readFile(job.file);res.writeHead(200,{'Content-Type':'video/mp4','Content-Length':data.length,'Content-Disposition':'attachment; filename="commercial.mp4"'});res.end(data);return true}json(res,200,{id:job.id,status:job.status,message:job.message,error:job.error});return true}json(res,404,{error:'Not found'});return true}
