import {commercialHandler} from './commercial.js';
import http from 'node:http';
const PORT=process.env.PORT||3000;
const key=process.env.REPLICATE_API_TOKEN;
const model=process.env.REPLICATE_MODEL||'minimax/video-01';
const jobs=new Map();
const page=String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Video Studio</title><style>
:root{font-family:Inter,system-ui,Arial;background:#080c10;color:#f4f8f7}*{box-sizing:border-box}body{margin:0}header{border-bottom:1px solid #24332e;padding:22px 6%;display:flex;justify-content:space-between;align-items:center}.brand{font-size:22px;font-weight:850}.brand b{color:#42df8e}.tag{color:#8ba99b;font-size:12px}main{max-width:950px;margin:50px auto;padding:0 22px}h1{font-size:clamp(32px,6vw,58px);margin:0 0 12px}p{color:#9fb1ab;line-height:1.6}.card{background:#111b1a;border:1px solid #263c33;border-radius:22px;padding:26px;margin-top:30px}label{display:block;margin:18px 0 9px;font-weight:650}textarea,select,input{width:100%;background:#08110f;color:white;border:1px solid #345244;border-radius:12px;padding:14px;font:inherit}textarea{height:160px;resize:vertical}button{background:#3be28a;border:0;border-radius:12px;padding:15px 24px;font-weight:800;cursor:pointer;margin-top:22px;width:100%;font-size:16px}button:disabled{opacity:.5;cursor:wait}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.output{margin-top:28px;display:none}.output video{width:100%;border-radius:14px;margin-top:12px}.status{padding:12px;border-radius:10px;background:#0b2820;color:#a8f7cd}.download{color:#45e990;display:inline-block;margin-top:12px}@media(max-width:600px){.grid{grid-template-columns:1fr}header{padding:18px 22px}.card{padding:18px}}</style></head><body><header><div class="brand">✦ AI <b>VIDEO</b> STUDIO</div><span class="tag">CREATE • GENERATE • EXPORT</span></header><main><p><a href="/commercial" style="color:#42df8e;font-weight:700">🎬 Create a 30-second commercial →</a></p><h1>Turn ideas into <span style="color:#42df8e">motion.</span></h1><p>Describe your scene. Generate an AI-powered video and download the result.</p><div class="card"><label for="prompt">Describe your video</label><textarea id="prompt" maxlength="2000" placeholder="A cinematic aerial shot of a futuristic city at sunset, realistic lighting, smooth camera movement..."></textarea><div class="grid"><div><label for="style">Visual style</label><select id="style"><option>Cinematic</option><option>Photorealistic</option><option>Animation</option><option>Commercial</option><option>Documentary</option></select></div><div><label for="ratio">Aspect ratio</label><select id="ratio"><option value="16:9">16:9 • Landscape</option><option value="9:16">9:16 • Vertical</option><option value="1:1">1:1 • Square</option></select></div></div><button id="go">Generate video →</button><div id="output" class="output"><div id="status" class="status" role="status" aria-live="polite"></div><video id="video" controls playsinline style="display:none"></video><a id="download" class="download" style="display:none" target="_blank" rel="noopener">Open / download video ↗</a></div></div><p style="font-size:13px">Powered by a configurable Replicate video model. Generation requires a server-side API token and incurs provider charges. Model capabilities and aspect ratios vary.</p></main><script>
const go=document.querySelector('#go'),out=document.querySelector('#output'),status=document.querySelector('#status'),video=document.querySelector('#video'),download=document.querySelector('#download');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
go.onclick=async()=>{const prompt=document.querySelector('#prompt').value.trim();if(!prompt){alert('Enter a video description.');return}go.disabled=true;out.style.display='block';video.style.display='none';download.style.display='none';status.textContent='Submitting generation request…';try{let r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,style:document.querySelector('#style').value,ratio:document.querySelector('#ratio').value})});let data=await r.json();if(!r.ok)throw Error(data.error||'Generation failed');for(let i=0;i<120;i++){status.textContent='AI video generation in progress… ('+data.status+')';if(data.status==='succeeded'){let url=Array.isArray(data.output)?data.output.find(v=>typeof v==='string'):data.output;if(typeof url!=='string')throw Error('Video provider returned no downloadable URL');video.src=url;video.style.display='block';download.href=url;download.style.display='inline-block';status.textContent='Video ready!';return}if(['failed','canceled'].includes(data.status))throw Error(data.error||'Generation failed');await sleep(5000);r=await fetch('/api/status/'+encodeURIComponent(data.id));data=await r.json();if(!r.ok)throw Error(data.error||'Unable to check status')}throw Error('Still processing. Please retry generation later.')}catch(e){status.textContent=e.message}finally{go.disabled=false}};
</script></body></html>`;
function send(res,code,data,type='application/json'){res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(type==='application/json'?JSON.stringify(data):data)}
async function provider(path,options={}){const r=await fetch('https://api.replicate.com/v1/'+path,{...options,headers:{Authorization:'Bearer '+key,'Content-Type':'application/json',Prefer:'wait=1',...options.headers}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||'Provider error ('+r.status+')');return d}
http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');if(await commercialHandler(req,res,url))return;if(req.method==='GET'&&url.pathname==='/'){return send(res,200,page,'text/html; charset=utf-8')}if(req.method==='GET'&&url.pathname==='/health'){return send(res,200,{ok:true,providerConfigured:!!key})}
if(req.method==='POST'&&url.pathname==='/api/generate'){if(!key)return send(res,503,{error:'Video generation is not configured. Add REPLICATE_API_TOKEN in Render environment variables.'});let body='';try{for await(const chunk of req){body+=chunk;if(body.length>10000)throw Error('Request too large')}const d=JSON.parse(body);if(typeof d.prompt!=='string'||!d.prompt.trim()||d.prompt.length>2000)return send(res,400,{error:'Prompt must be 1–2000 characters'});const [owner,name]=model.split('/');if(!owner||!name)throw Error('Invalid REPLICATE_MODEL');const prompt=d.prompt.trim()+'; visual style: '+String(d.style||'cinematic').slice(0,40)+'; aspect ratio: '+String(d.ratio||'16:9').slice(0,10);const prediction=await provider('models/'+encodeURIComponent(owner)+'/'+encodeURIComponent(name)+'/predictions',{method:'POST',body:JSON.stringify({input:{prompt}})});jobs.set(prediction.id,Date.now());return send(res,200,{id:prediction.id,status:prediction.status,output:prediction.output,error:prediction.error})}catch(e){return send(res,400,{error:e.message})}}
if(req.method==='GET'&&url.pathname.startsWith('/api/status/')){if(!key)return send(res,503,{error:'Provider not configured'});const id=url.pathname.split('/').pop();if(!jobs.has(id))return send(res,404,{error:'Unknown job'});try{const d=await provider('predictions/'+encodeURIComponent(id));return send(res,200,{id:d.id,status:d.status,output:d.output,error:d.error})}catch(e){return send(res,502,{error:e.message})}}
return send(res,404,{error:'Not found'})}).listen(PORT,'0.0.0.0',()=>console.log('AI Video Studio listening on '+PORT));
